### PR TITLE
Add tuple test cases

### PR DESCRIPTION
**Pull request by ushirask**
## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Comment by jclark** [comment]
Also need to handle `[T1, T2, T...]` case.

Should check e.g. `[int, int...]` is a subtype of `[int...]`.

**Comment by jclark** [comment]
Is this ready?

**Comment by ushirask** [comment]
> Is this ready?

@jclark  When testing [T, T...] and [T...] they are shown as subtypes of each other, shouldn't it be a proper subtype?

**Comment by jclark** [comment]
Should be proper subtype.

**Comment by jclark** [comment]
Create an issue for the subtyping problem with [T, T...] and [T...]. See if it happens before change to add fixed length array types.  Also see if it happens with JSON syntax.

**Pull request merged**
