### PR TITLE
Sync with ballerina lang change

### PR DESCRIPTION
**Pull request by pcnfernando**
## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Comment by jclark** [comment]
Hmm. The new Ballerina code doesn't look nice to me. I think we need to discuss this further cc @hasithaa.

**Comment by jclark** [comment]
This may be a spec problem. I remember we had a discussion about this.

**Comment by pcnfernando** [comment]
The discussion is under https://github.com/ballerina-platform/ballerina-spec/issues/871

**Comment by jclark** [comment]
Conclusion is that there was a misunderstanding about the spec and the current nballerina code is OK.

**Pull request closed without merging**
