### PR TITLE
Set TypeTag for PackageCpInfo in BIRReader

### PR DESCRIPTION
**Pull request by shubhamnarlawar**
This PR resolves issue #44

### CODE REVIEW

**Comment by ruvi-d** [comment]
Looking into it further, the `tagEnum tag` for other `CpInfo` types are also not being set. I am assuming that this means that all the `assert(poolEntry->getTag() ` checks will fail in the `ConstantPoolSet::get*` methods starting from: https://github.com/ballerina-platform/nballerina/blob/cffea5f6036e4d4691ba0d20481e948d62df9617/BIR2llvmIR/BIRReader.cpp#L97

How about we set the correct tag in the constructor for each `CpInfo` type? That should address this.

**Comment by ayonam** [comment]
Yes, that was the original intent of the design.  The constructor
    will set it and all subsequent accesses will assert on that.
    
      
      
    
    On 27/01/21 18:44, Ruvinda Dhambarage
      wrote:
    
    
      
      Looking into it further, the tagEnum tag for
        other CpInfo types are also not being set. I am
        assuming that this means that all the assert(poolEntry->getTag()
         checks will fail in the ConstantPoolSet::get*
        methods starting from: https://github.com/ballerina-platform/nballerina/blob/cffea5f6036e4d4691ba0d20481e948d62df9617/BIR2llvmIR/BIRReader.cpp#L97
      How about we set the correct tag in the constructor for each CpInfo
        type? That should address this.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ballerina-platform/nballerina/pull/46#issuecomment-768277049",
"url": "https://github.com/ballerina-platform/nballerina/pull/46#issuecomment-768277049",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Review by ruvi-d — CHANGES_REQUESTED** [review]
Let's update the constructor for each CpInfo type and set the correct tag.

**Comment by shubhamnarlawar** [comment]
> Let's update the constructor for each CpInfo type and set the correct tag.

Done. Please check it!

**Comment by shubhamnarlawar** [comment]
> Looking into it further, the `tagEnum tag` for other `CpInfo` types are also not being set. I am assuming that this means that all the `assert(poolEntry->getTag() ` checks will fail in the `ConstantPoolSet::get*` methods starting from:
> 
> https://github.com/ballerina-platform/nballerina/blob/cffea5f6036e4d4691ba0d20481e948d62df9617/BIR2llvmIR/BIRReader.cpp#L97
> 
> How about we set the correct tag in the constructor for each `CpInfo` type? That should address this.

I have updated the assert statement as well.

**Comment by shubhamnarlawar** [comment]
This PR resolved the issue #44

**Comment by shubhamnarlawar** [comment]
@ruvi-d - Is this PR good to merge

**Review by ruvi-d — APPROVED** [review]
Good to merge PR

**Comment by shubhamnarlawar** [comment]
@uthaiyashankar - Request to merge this PR.

**Review by uthaiyashankar — APPROVED** [review]

**Pull request merged**
