### PR TITLE
Hotfix debug build failure on master

### PR DESCRIPTION
**Pull request by ruvi-d**
## Purpose
$subject

### CODE REVIEW

**Review by shubhamnarlawar — APPROVED** [review]

**Comment by shubhamnarlawar** [comment]
There is no break statement in above switch case - i.e. in `TYPE_TAG_RECORD`

https://github.com/ballerina-platform/nballerina/blob/d3c630956da461a0b2b0d5cbc3a06791cd569bc7/compiler/BIRReader.cpp#L1018

**Comment by ruvi-d** [comment]
> There is no break statement in above switch case - i.e. in `TYPE_TAG_RECORD`

Let me add a fix here

**Comment by shubhamnarlawar** [comment]
One more thing - Please run clang-format on `BIRReader`

I see an empty line here - 

https://github.com/ballerina-platform/nballerina/blob/d3c630956da461a0b2b0d5cbc3a06791cd569bc7/compiler/BIRReader.cpp#L1029

**Comment by ruvi-d** [comment]
> One more thing - Please run clang-format on `BIRReader`
> 
> I see an empty line here -
> 
> https://github.com/ballerina-platform/nballerina/blob/d3c630956da461a0b2b0d5cbc3a06791cd569bc7/compiler/BIRReader.cpp#L1029

I did run it. Thus the other formatting fixes in https://github.com/ballerina-platform/nballerina/pull/283/commits/7bfeaf3bf16a4f2d666919bf779ba4e7717a8ab0

Seems that this empty line is not getting picked up on my end. Suggest that we don't fix it with this PR as it's non functional.

**Comment by shubhamnarlawar** [comment]
> > One more thing - Please run clang-format on `BIRReader`
> > I see an empty line here -
> > https://github.com/ballerina-platform/nballerina/blob/d3c630956da461a0b2b0d5cbc3a06791cd569bc7/compiler/BIRReader.cpp#L1029
> 
> I did run it. Thus the other formatting fixes in [7bfeaf3](https://github.com/ballerina-platform/nballerina/commit/7bfeaf3bf16a4f2d666919bf779ba4e7717a8ab0)
> 
> Seems that this empty line is not getting picked up on my end. Suggest that we don't fix it with this PR as it's non functional.

Sure.

**Review by shubhamnarlawar — APPROVED** [review]

**Comment by shubhamnarlawar** [comment]
PR looks good to me.
Thanks for the changes.

**Pull request merged**
