### PR TITLE
Run LIT tests with sanitizers ON

### LINKED ISSUE #262: Run PR check LIT tests with sanitizers enabled
**Description:**

Enable sanitizers for nballerina binary when running PR checks. This will allow us to catch when a new PR introduces a memory leak or invokes undefined behavior. 

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by ruvi-d**
## Purpose

Run additional PR checks with sanitizers on to catch things like memory leaks, out of bounds memory access and the invocation of undefined behavior

Resolves #262

### CODE REVIEW

**Comment by shubhamnarlawar** [comment]
Does this mean there are no memory leaks, out of bounds memory access, etc in the master branch right now﹖

**Comment by ruvi-d** [comment]
> Does this mean there are no memory leaks, out of bounds memory access, etc in the master branch right now﹖

That's right

**Review by shubhamnarlawar — APPROVED** [review]
Changes looks good to me.

**Comment by shubhamnarlawar** [comment]
We can merge this PR first so that we can catch possible memory leaks from the open PR's.

**Pull request merged**
