### PR TITLE
Add LIT tests that uses runtime

### PR DESCRIPTION
**Pull request by shubhamnarlawar**
## Purpose
This PR adds support for LIT tests that checks runtime functions like -
1. `new_int_array()`
2. `int_array_store()`
3. `int_array_load()`

### CODE REVIEW

**Comment by shubhamnarlawar** [comment]
This PR resolve issues - #60 and #65

**Review by ruvi-d — CHANGES_REQUESTED** [review]
1) Please update the LIT test `// RUN` directive to match the one used in the other tests: `// RUN: JAVA_HOME=%java_path %testRunScript %s %nballerinacc | filecheck %s`

2) `// CHECK-SAME` is not correctly supported in the Python `filecheck`. So, please update then to `// CHECK: RETVAL=<test_value>` type. Please see the other tests for examples.

3) Shall we migrate these tests to use the print runtime functions instead of checking the return value?

**Comment by shubhamnarlawar** [comment]
> * Please update the LIT test `// RUN` directive to match the one used in the other tests: `// RUN: JAVA_HOME=%java_path %testRunScript %s %nballerinacc | filecheck %s`
> * `// CHECK-SAME` is not correctly supported in the Python `filecheck`. So, please update then to `// CHECK: RETVAL=<test_value>` type. Please see the other tests for examples.
> * Shall we migrate these tests to use the print runtime functions instead of checking the return value?

Sure. Let us send the suggested changes on above comments.

**Comment by shubhamnarlawar** [comment]
PR #71 is way beyond master. Hence, I have created a new PR #120 for issues being addressed in this PR.

**Comment by ruvi-d** [comment]
@shubhamnarlawar : you can close this PR if you don't what to merge it

**Comment by shubhamnarlawar** [comment]
Closing this PR.

**Pull request closed without merging**
