### PR TITLE
Add libbacktrace

### LINKED ISSUE #367: Add libbacktrace as third-party library
To support backtraces, we should add libbacktrace as a third-party library using the process described in third-party/README.md

This is a prerequisite for #46

### PR DESCRIPTION
**Pull request by KavinduZoysa**
## Purpose
Fixes #367

### CODE REVIEW

**Comment by manuranga** [comment]
Please add the submodule to a dir, not to top level. I suggest creating a dir named `trace`.
Please add a mapping file as well.

**Comment by KavinduZoysa** [comment]
> Please add the submodule to a dir, not to top level. I suggest creating a dir named `trace`.
> Please add a mapping file as well.

Fixed

**Review by jclark — COMMENTED** [review]
Fixing #372 also requires getting this onto the main branch and getting it to build with our Makefile.

**Comment by jclark** [comment]
@manuranga Please deal with merging it onto the third-party branch.

**Pull request merged**
