### PR TITLE
Annotate the test suite with labels

### LINKED ISSUE #425: Annotate test suite with labels
Each test file should contain set of labels similar to the labels used by the conformance tests.

### PR DESCRIPTION
**Pull request by manuranga**
Annotate the test suite with labels

Fixes #425

### CODE REVIEW

**Comment by manuranga** [comment]
@jclark I didn't quite understand your concern regarding labels being at the top of the file. Should it be moved to bottom?

I didn't remove the minimal subset, since I think that has to be a somewhat manual task. But I did organize labels by the subset, so relevant ones should be at the beginning.

**Comment by jclark** [comment]
I thought we decided that our labels were coming from the spreadsheet not just production names.

Going forward, I think we will want to add `@labels` that are consistent with those used by the conformance test suite.  However, fixing up our current tests to do this is not a priority task for us. So I think the pragmatic solution is to put in the labels as you have them in this PR, but call it `@productions`. At some later date, we (or @MaryamZi's team) can use these `@productions` to generate `@labels`.

My point about beginning vs end was only that adding a line at the beginning would change the debug info in the .ll file (but I haven't added that yet).

**Comment by manuranga** [comment]
I missed that you have edited the above comment. I update the labels to have non-production items as well.

**Comment by jclark** [comment]
I looked at a few, and they are still some way from having a correct set of labels, so I still think what I suggested is better.

**Comment by manuranga** [comment]
Let me break the current ones into `@productions` and `@labels`

**Comment by manuranga** [comment]
[I created this graph to show implications in the current set of labels.](https://dreampuf.github.io/GraphvizOnline/#digraph%20G%20%7B%0A%22int-literal%22%0A%22local-var-decl-stmt%22%0A%22assign-stmt%22%0A%22function-call-expr%22%0A%22any%22%0A%22additive-expr%22%0A%22unary-expr%22%0A%22unary-minus%22%0A%22return-stmt%22%0A%22boolean-literal%22%0A%22relational-expr%22%0A%22floating-point-literal%22%0A%22equality-expr%22%0A%22if-else-stmt%22%0A%22multiplicative-expr%22%0A%22equality%22%0A%22boolean%22%0A%22exact-equality%22%0A%22break-stmt%22%0A%22while-stmt%22%0A%22unary-not%22%0A%22continue-stmt%22%0A%22type-cast-expr%22%0A%22bitwise-or-expr%22%0A%22bitwise-and-expr%22%0A%22bitwise-xor-expr%22%0A%22list-constructor-expr%22%0A%22range-expr%22%0A%22foreach-stmt%22%0A%22list-type-descriptor%22%0A%22null%22%0A%22array%3Alength%22%0A%22array%3Apush%22%0A%22final-local-var-decl-stmt%22%0A%22string-literal%22%0A%22string%22%0A%22mapping-constructor-expr%22%0A%22StringNumericEscape%22%0A%22string%3Alength%22%0A%22map-type-descriptor%22%0A%22int%3AtoHexString%22%0A%22map%3Alength%22%0A%22match-stmt%22%0A%22is-expr%22%0A%22module-const-decl%22%0A%22unary-complement%22%0A%22compound-assignment-stmt%22%0A%22float%22%0A%22is-not-expr%22%0A%22infinite%22%0A%22nan%22%0A%22shift-expr%22%0A%22error-constructor-expr%22%0A%22panic-stmt%22%0A%22error%3Amessage%22%0A%22panic-stmt%22%20-%3E%20%22string-literal%22%0A%22panic-stmt%22%20-%3E%20%22error-constructor-expr%22%0A%22range-expr%22%20-%3E%20%22int-literal%22%0A%22while-stmt%22%20-%3E%20%22int-literal%22%0A%22shift-expr%22%20-%3E%20%22int-literal%22%0A%22bitwise-and-expr%22%20-%3E%20%22int-literal%22%0A%22break-stmt%22%20-%3E%20%22int-literal%22%0A%22bitwise-xor-expr%22%20-%3E%20%22int-literal%22%0A%22map%3Alength%22%20-%3E%20%22int-literal%22%0A%22array%3Apush%22%20-%3E%20%22int-literal%22%0A%22match-stmt%22%20-%3E%20%22int-literal%22%0A%22unary-complement%22%20-%3E%20%22int-literal%22%0A%22foreach-stmt%22%20-%3E%20%22int-literal%22%0A%22bitwise-or-expr%22%20-%3E%20%22int-literal%22%0A%22int%3AtoHexString%22%20-%3E%20%22int-literal%22%0A%22is-not-expr%22%20-%3E%20%22int-literal%22%0A%22continue-stmt%22%20-%3E%20%22int-literal%22%0A%22nan%22%20-%3E%20%22floating-point-literal%22%0A%22infinite%22%20-%3E%20%22floating-point-literal%22%0A%22map%3Alength%22%20-%3E%20%22string-literal%22%0A%22error-constructor-expr%22%20-%3E%20%22string-literal%22%0A%22StringNumericEscape%22%20-%3E%20%22string-literal%22%0A%22string%3Alength%22%20-%3E%20%22string-literal%22%0A%22error%3Amessage%22%20-%3E%20%22string-literal%22%0A%22foreach-stmt%22%20-%3E%20%22range-expr%22%0A%22range-expr%22%20-%3E%20%22foreach-stmt%22%0A%22nan%22%20-%3E%20%22unary-expr%22%0A%22nan%22%20-%3E%20%22infinite%22%0A%22nan%22%20-%3E%20%22unary-minus%22%0A%22nan%22%20-%3E%20%22multiplicative-expr%22%0A%22shift-expr%22%20-%3E%20%22local-var-decl-stmt%22%0A%22map%3Alength%22%20-%3E%20%22mapping-constructor-expr%22%0A%22map-type-descriptor%22%20-%3E%20%22mapping-constructor-expr%22%0A%22bitwise-and-expr%22%20-%3E%20%22local-var-decl-stmt%22%0A%22unary-not%22%20-%3E%20%22unary-expr%22%0A%22unary-complement%22%20-%3E%20%22unary-expr%22%0A%22infinite%22%20-%3E%20%22unary-expr%22%0A%22unary-minus%22%20-%3E%20%22unary-expr%22%0A%22bitwise-xor-expr%22%20-%3E%20%22local-var-decl-stmt%22%0A%22map%3Alength%22%20-%3E%20%22local-var-decl-stmt%22%0A%22map%3Alength%22%20-%3E%20%22boolean-literal%22%0A%22map%3Alength%22%20-%3E%20%22map-type-descriptor%22%0A%22exact-equality%22%20-%3E%20%22equality-expr%22%0A%22array%3Apush%22%20-%3E%20%22local-var-decl-stmt%22%0A%22array%3Apush%22%20-%3E%20%22list-type-descriptor%22%0A%22array%3Apush%22%20-%3E%20%22list-constructor-expr%22%0A%22null%22%20-%3E%20%22local-var-decl-stmt%22%0A%22list-type-descriptor%22%20-%3E%20%22local-var-decl-stmt%22%0A%22unary-complement%22%20-%3E%20%22local-var-decl-stmt%22%0A%22array%3Alength%22%20-%3E%20%22local-var-decl-stmt%22%0A%22int%3AtoHexString%22%20-%3E%20%22local-var-decl-stmt%22%0A%22compound-assignment-stmt%22%20-%3E%20%22local-var-decl-stmt%22%0A%22error%3Amessage%22%20-%3E%20%22local-var-decl-stmt%22%0A%22map-type-descriptor%22%20-%3E%20%22local-var-decl-stmt%22%0A%22null%22%20-%3E%20%22equality-expr%22%0A%22null%22%20-%3E%20%22function-call-expr%22%0A%22null%22%20-%3E%20%22equality%22%0A%22null%22%20-%3E%20%22any%22%0A%22null%22%20-%3E%20%22return-stmt%22%0A%22list-type-descriptor%22%20-%3E%20%22list-constructor-expr%22%0A%22array%3Alength%22%20-%3E%20%22list-type-descriptor%22%0A%22unary-complement%22%20-%3E%20%22unary-minus%22%0A%22unary-complement%22%20-%3E%20%22function-call-expr%22%0A%22unary-complement%22%20-%3E%20%22int%3AtoHexString%22%0A%22unary-complement%22%20-%3E%20%22return-stmt%22%0A%22array%3Alength%22%20-%3E%20%22list-constructor-expr%22%0A%22infinite%22%20-%3E%20%22unary-minus%22%0A%22infinite%22%20-%3E%20%22multiplicative-expr%22%0A%22error%3Amessage%22%20-%3E%20%22error-constructor-expr%22%0A%22equality%22%20-%3E%20%22equality-expr%22%0A%22continue-stmt%22%20-%3E%20%22equality-expr%22%0A%22continue-stmt%22%20-%3E%20%22equality%22%0A%22is-not-expr%22%20-%3E%20%22is-expr%22%0A%22continue-stmt%22%20-%3E%20%22if-else-stmt%22%0A%7D)
graphviz
While some of them are inherent to ballerina (eg `range-expr` <-> `foreach-stmt`) others show that our testSuite is not granular enough.

**Pull request merged**
