### PR TITLE
Add generated regex tests as long running tests

### PR DESCRIPTION
**Pull request by heshanpadmasiri**
## Purpose
Add generated regex tests as long running tests
Related to #1076.

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Comment by heshanpadmasiri** [comment]
@jclark I only added the test case for #1076. I will update the `regexGeneratedTests.json` with the other test cases once #1075 is fixed.

**Comment by jclark** [comment]
Since we haven't really solved the underlying problem that causes us to handle these inefficiently, I think we should have these tests (and some others) in the repo but not enable them.

**Comment by heshanpadmasiri** [comment]
> Since we haven't really solved the underlying problem that causes us to handle these inefficiently, I think we should have these tests (and some others) in the repo but not enable them.

Sorry for the late response I didn't see this. Fixed

**Comment by jclark** [comment]
Let's figure out what to do here when we finish fixing this problem.

**Pull request closed without merging**
