### PR TITLE
Add AST serialization for function def

### PR DESCRIPTION
**Pull request by manuranga**
Draft of AST json serialization. Opened for preliminary feedback.

Part of #50

### CODE REVIEW

**Comment by jclark** [comment]
I would suggest using Ballerina keywords as much as possible: so `var` instead of `var-decl`; `return` instead of `ret`.

For function qualifiers like "public": I would use a sorted list of qualifiers. So with subset 1, either `["public"]` or `[]`.

**Comment by manuranga** [comment]
I am planing to add a flag to CLI that will write the ast json to a file, so we can use it from `compile.sh`.

**Comment by jclark** [comment]
CLI flag is good, but why do you want to use it from `compile.sh`?

**Comment by jclark** [comment]
Sorry I pressed the wrong button

**Comment by manuranga** [comment]
I was thinking to keep the ast jsons in `test/ast` dir simile to the ll files (perhaps not for all cases) and verify them using `diff`.

**Comment by jclark** [comment]
Presumably we are going to have parse tests, together with expected output that we have manually written, in the front module; then testerina will check that.

If we have that, I'm not convinced saving the ast in test/ast is going to be of much practical benefit.

**Comment by jclark** [comment]
On second thoughts, perhaps it could be set up in a way that would be useful, e.g. when you run the tests, if one or more ASTs have changed, it will print a message saying "the ASTs for 17 files have changed", and if that's not expected, you can do something about it.  We should probably do the same for `.ll`.

**Comment by manuranga** [comment]
putting this on hold in favor of #84

**Pull request closed without merging**
