### PR TITLE
Translation of BIR to LLVM IR

### PR DESCRIPTION
**Pull request by shubhamnarlawar**
Purpose

    Implementation of nballerina compiler.

Goals

    Translation of Ballerina IR to LLVM IR.

Approach

    Created a BIRReader class which reads BIR from the binary dump and store it in the object of BIRPackage class defined in BIR.h

Purpose of BIRReader class -

a. Reads Constant Pool entries.
b. Reads Module consisting of functions, basic blocks and instructions.

BIRPackage class consist of translate() function which translates functions, basic blocks and instructions to the LLVM IR.

### CODE REVIEW

**Comment by shubhamnarlawar** [comment]
@Kishanthan - Please review and suggest changes.

**Comment by Kishanthan** [comment]
@shubhamnarlawar , this PR it still show 5000+ files changed. Can you check and verify? Since we have merged the LLVM source already, this shouldn't have such large files changed.

**Comment by ramakotareddy** [comment]
> @shubhamnarlawar , this PR it still show 5000+ files changed. Can you check and verify? Since we have merged the LLVM source already, this shouldn't have such large files changed.

I will check it and get back to you.

**Comment by shubhamnarlawar** [comment]
> @shubhamnarlawar , this PR it still show 5000+ files changed. Can you check and verify? Since we have merged the LLVM source already, this shouldn't have such large files changed.

I will check this issue and get back to you.

**Pull request closed without merging**
