### PR TITLE
Remove LLVM source code

### LINKED ISSUE #51: Remove LLVM source code from repo
**Description:**
The `llvm-project-master` folder containing the LLVM source code needs to be removed from the source tree. The LLVM standard binary release should be used to compile the nBallerina project instead.  

**Suggested Assignees:**
ruvi-d

### PR DESCRIPTION
**Pull request by ruvi-d**
## Purpose
Resolves #51, #16 

## Goals
* Remove the llvm-project source tree from repo
* Use Ubuntu's bundled llvm-11-dev package for compiling project
* Add top level CMake file that can later be extended to support multiple target platforms

## Notes
This will break the existing Github workflow PR check

### CODE REVIEW

**Comment by shubhamnarlawar** [comment]
This PR failed with below error - 

`CMake Error: The source directory "/home/runner/work/nballerina/nballerina/llvm-project-master/llvm" does not exist.`

**Comment by ruvi-d** [comment]
> This PR failed with below error -
> 
> `CMake Error: The source directory "/home/runner/work/nballerina/nballerina/llvm-project-master/llvm" does not exist.`

Yeah.. I've mentioned that Github PR check will failed since the LLVM project source was removed. I suppose the corresponding Github actions update should come after this?

**Comment by ruvi-d** [comment]
> > This PR failed with below error -
> > `CMake Error: The source directory "/home/runner/work/nballerina/nballerina/llvm-project-master/llvm" does not exist.`
> 
> Yeah.. I've mentioned that Github PR check will failed since the LLVM project source was removed. I suppose the corresponding Github actions update should come after this?

Updated PR check to work without the LLVM source code
@shubhamnarlawar : Please review the changes

**Comment by shubhamnarlawar** [comment]
> > > This PR failed with below error -
> > > `CMake Error: The source directory "/home/runner/work/nballerina/nballerina/llvm-project-master/llvm" does not exist.`
> > 
> > 
> > Yeah.. I've mentioned that Github PR check will failed since the LLVM project source was removed. I suppose the corresponding Github actions update should come after this?
> 
> Updated PR check to work without the LLVM source code
> @shubhamnarlawar : Please review the changes

This looks good.

But for unit tests in LIT to work, some part of llvm source code is required. Please refer #47. If we remove complete llvm source now, then LIT unit tests will not work.

I think this PR is good to merge in master when LIT unit tests are independent of LLVM source code. WDYT?

**Comment by ruvi-d** [comment]
> I think this PR is good to merge in master when LIT unit tests are independent of LLVM source code. WDYT?

@shubhamnarlawar : I am not clear regarding the impact to #47. How do you executed those unit tests at the moment? and what are the options to execute them if we remove the LLVM source code with this PR?

**Comment by shubhamnarlawar** [comment]
> > I think this PR is good to merge in master when LIT unit tests are independent of LLVM source code. WDYT?
> 
> @shubhamnarlawar : I am not clear regarding the impact to #47. How do you executed those unit tests at the moment? and what are the options to execute them if we remove the LLVM source code with this PR?

From the start, we do manual testing as below - 

`./nballerinacc $FILE_NAME && clang $FILE_NAME.ll && ./a.out`
`echo $?`

#47 - makes use of LLVM LIT framework which eliminates above manual process.
If we remove llvm source, then we will not be able to use LIT framework right?

Hope this clears your query!

**Comment by ayonam** [comment]
Yes, that is the problem with removing these sources.  We cannot
      use the LIT framework.  We should explore how to extricate the LIT
      framework and hold that alone in our Repo.  I think it only needs
      one particular directory that holds the framework code in Python
      and then some configuration files in some predefined relative
      paths.  We can then take those files alone and add them to our
      source tree.
    
    
    
    
    On 28/01/21 13:16, shubhamnarlawar
      wrote:
    
    
      
      
        
          I think this PR is good to merge in master when LIT unit
            tests are independent of LLVM source code. WDYT?
        
        @shubhamnarlawar : I am not clear
          regarding the impact to #47. How do you executed those
          unit tests at the moment? and what are the options to execute
          them if we remove the LLVM source code with this PR?
      
      From the start, we do manual testing as below -
      ./nballerinacc $FILE_NAME && clang $FILE_NAME.ll
          && ./a.out
        echo $?
      #47 - makes use of LLVM LIT
        framework which eliminates above manual process.
        If we remove llvm source, then we will not be able to use LIT
        framework right?
      Hope this clears your query!
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ballerina-platform/nballerina/pull/52#issuecomment-768866480",
"url": "https://github.com/ballerina-platform/nballerina/pull/52#issuecomment-768866480",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ruvi-d** [comment]
> Yes, that is the problem with removing these sources.  We cannot use the LIT framework.  We should explore how to extricate the LIT framework and hold that alone in our Repo.  I think it only needs one particular directory that holds the framework code in Python and then some configuration files in some predefined relative paths.  We can then take those files alone and add them to our source tree. 

There is a standalone Python package for running LIT tests out of source https://pypi.org/project/lit/. 
I also found some instructions to integrate with CMake too : https://medium.com/@mshockwave/using-llvm-lit-out-of-tree-5cddada85a78
Let me add support to our repo and update this PR.

**Comment by ruvi-d** [comment]
I think we are good now. @shubhamnarlawar please verify.

**Comment by ayonam** [comment]
Yes, this sounds like a good idea.  Please check if our tests run
    with this framework.  You may need to modify some configuration
    scripts which contain the relative paths.
    
      
      
    
    On 29/01/21 12:55, Ruvinda Dhambarage
      wrote:
    
    
      
      
        Yes, that is the problem with removing these sources.  We
          cannot use the LIT framework.  We should explore how to
          extricate the LIT framework and hold that alone in our Repo. 
          I think it only needs one particular directory that holds the
          framework code in Python and then some configuration files in
          some predefined relative paths.  We can then take those files
          alone and add them to our source tree.
      
      There is a standalone Python package for running LIT tests out
        of source https://pypi.org/project/lit/.
        I also found some instructions to integrate with CMake too : https://medium.com/@mshockwave/using-llvm-lit-out-of-tree-5cddada85a78
        Let me add support to our repo and update this PR.
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ballerina-platform/nballerina/pull/52#issuecomment-769630643",
"url": "https://github.com/ballerina-platform/nballerina/pull/52#issuecomment-769630643",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ruvi-d** [comment]
@ayonam Yes I was able merge the LIT test PR on top of this and run the tests. I've committed those changes to https://github.com/ruvi-d/nballerina/tree/ruvi/test/lit-test 
However, I am not gonna add that to this PR since some test fail (7/28) due to nballerina compiling error. Let's handle that in a separate PR. 

@shubhamnarlawar : please verify changes from this PR

**Comment by ruvi-d** [comment]
Considering multi-platform support we might have to reconsider this PR. I've started #53 to discuss this. Please post your ideas there.

**Comment by ruvi-d** [comment]
#53 is resolved

**Comment by shubhamnarlawar** [comment]
> @ayonam Yes I was able merge the LIT test PR on top of this and run the tests. I've committed those changes to https://github.com/ruvi-d/nballerina/tree/ruvi/test/lit-test
> However, I am not gonna add that to this PR since some test fail (7/28) due to nballerina compiling error. Let's handle that in a separate PR.
> 
> @shubhamnarlawar : please verify changes from this PR

This LGTM. If all the tests are passing, then we are good to go with this PR. WDYT?

**Comment by shubhamnarlawar** [comment]
@ruvi-d - There are some conflicts with the master. Can you check it?

**Comment by ruvi-d** [comment]
> @ruvi-d - There are some conflicts with the master. Can you check it?

Yes will do. The LIT PR merge broke this PR. Will merge and update this PR.

**Comment by ayonam** [comment]
@shubhamnarlawar: Thanks Shubham for this update.  What is the
    reason for the failure in nballerina?  Have you triaged it? 
    
      
      
      
    
    On 02/02/21 19:17, shubhamnarlawar
      wrote:
    
    
      
      
        @ayonam
          Yes I was able merge the LIT test PR on top of this and run
          the tests. I've committed those changes to https://github.com/ruvi-d/nballerina/tree/ruvi/test/lit-test
          However, I am not gonna add that to this PR since some test
          fail (7/28) due to nballerina compiling error. Let's handle
          that in a separate PR.
        @shubhamnarlawar : please verify
          changes from this PR
      
      This LGTM. If all the tests are passing, then we are good to go
        with this PR. WDYT?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ballerina-platform/nballerina/pull/52#issuecomment-771645664",
"url": "https://github.com/ballerina-platform/nballerina/pull/52#issuecomment-771645664",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ruvi-d** [comment]
@ayonam Let me check out the failing test cases and get back to you guys. On first glance it appears that the test that are not setting the `int _bal_result` value are the ones that are failing. I'll get back to you guys with some more info tomorrow.

**Comment by ruvi-d** [comment]
Hey @ayonam and @shubhamnarlawar : regarding the failing LIT tests on my end..
The `simpleMain.bal` and `floatTypecast.bal` are what are failing for me with the latest patches. `simpleMain.bal` is expecting `128` return value but I am getting `16`. nballerinacc throws the following error for `floatTypecast.bal`.
```
nballerinacc: /home/ruvinda/projects/nballerina/BIR2llvmIR/BIRReader.cpp:120: float ConstantPoolSet::getFloatCp(uint32_t): Assertion `poolEntry->getTag() != ConstantPoolEntry::tagEnum::TAG_ENUM_CP_ENTRY_FLOAT' failed
```

**Comment by ruvi-d** [comment]
I've updated this PR merging the latest changes to master. I have also added support to build our Rust runtime via Cargo and CMake. The previously mentioned two LIT tests are still failing. So, I've renamed their extension to `.skip` temporarily.

@shubhamnarlawar : please review these changes and also look at the two failing tests. You may have to refer the updated README for instructions on how to do build and test.

**Comment by ruvi-d** [comment]
@shubhamnarlawar : if troubleshooting the two test failures will take time, we can open issues to track them and pass this PR through.

**Comment by shubhamnarlawar** [comment]
> I've updated this PR merging the latest changes to master. I have also added support to build our Rust runtime via Cargo and CMake. The previously mentioned two LIT tests are still failing. So, I've renamed their extension to `.skip` temporarily.
> 
> @shubhamnarlawar : please review these changes and also look at the two failing tests. You may have to refer the updated README for instructions on how to do build and test.

The two testcases are failing because of following support - 

1. simpleMain.bal - From the observation, I suspect echo $? is returning separate values for Linux and Mac. We are using Linux which returns 128 and you are using Mac env which is returning 16 because this testcase is a empty testcase with just main function.

2. floatTypecast.bal - In this testcase, echo $? is not working in float types and hence this test is failing.

I think once we remove echo $? and use rust print routines, these two testcases will pass.

**Comment by shubhamnarlawar** [comment]
@ruvi-d - This PR looks good to me.
The PR consists many changes. Let us keep two failing testcases with `.skip` ext. WDYT?

**Comment by ruvi-d** [comment]
> @ruvi-d - This PR looks good to me.
> The PR consists many changes. Let us keep two failing testcases with `.skip` ext. WDYT?

Sounds good 👍

**Comment by shubhamnarlawar** [comment]
> @shubhamnarlawar : if troubleshooting the two test failures will take time, we can open issues to track them and pass this PR through.

Sure.

**Comment by ruvi-d** [comment]
Updated PR with latest changes to master. This PR is ready to be merged.

**Review by uthaiyashankar — APPROVED** [review]

**Pull request merged**
