### PR TITLE
Move build artifacts to a separate directory

### PR DESCRIPTION
**Pull request by manuranga**
This pr will

- Move build artifacts to a separate directory to keep the source dirs clean.
- [Quote](http://mywiki.wooledge.org/Quotes) variables to avoid potential issues 
- Make it possible to run from the root of the repository

### CODE REVIEW

**Comment by jclark** [comment]
Why did you kill my .gitignore?

**Comment by manuranga** [comment]
Ahh sorry, I didn't realize that you are running it manually as well. I removed it since the script no longer needs it because all temp files are getting created in a `target` dir. Will correct it in the next PR.

**Comment by jclark** [comment]
No problems, I put it back already.

**Comment by jclark** [comment]
I reverted this. It is not working for my workflow.

**Pull request merged**
